page:
    A4:
        top_margin: 0
        bottom_margin: 1
        left_margin: 1
        right_margin: 0
        inner_margin: 1
        length: 60
        width: 80
        line_break: !!python/unicode "\n"
        page_break: !!python/unicode "\f"


    braille_A4:
        inherits_from: A4
        width: 30
        length: 29
        bottom_margin: 0

    default:
        inherits_from: A4




    
footer:
    default:
        pagenum_cfg:
            height_mode: fixed
            lines_below: 0
            max_height: 1
            max_width: 0
            right_indent: 0
            width_mode: auto
            x_align: right
            x_hook: right
            x_offset: 0
            y_align: top
            y_hook: top
            y_offset: 0
        pagenumcontent_cfg: {}
        
        
frame:
    
    standard:
        height_mode: auto
        lines_below: 0
        max_height: 0
        max_width: 0
        right_indent: 0
        width_mode: fixed
        x_align: left
        x_hook: left
        x_offset: 0
        y_align: top
        y_hook: bottom
        y_offset: 0

    body0:
        inherits_from: standard
        
    default:
        inherits_from: body0
        
    body1:
        inherits_from: body0
    
    
    # frames for section containers
    
    section_container1:
        inherits_from: standard
        y_offset: 1
        lines_below: 2

        
    section_container2:
        inherits_from: standard
        lines_below: 1
        
    section_container3:
        inherits_from: section_container2
        x_offset: 2
        
    section_container4:
        inherits_from: section_container3
        x_offset: 4

    section_container5:
        inherits_from: section_container4


    document_title:
        inherits_from: standard
        y_offset: 1
        lines_below: 3


    
        
    # frames  for section titles
    section_title1:
        inherits_from: standard
        lines_below: 1
        
    section_title2:
        inherits_from: section_title1
        x_offset: 2

    section_title3:
        inherits_from: section_title2

    section_title4:
        inherits_from: section_title3
        
    section_title5:
        inherits_from: section_title3
        

    topic:
        inherits_from: section_title5

    glossary_term:
        inherits_from: standard
        

    glossary_definition:
        inherits_from: standard
        x_offset: 2

    # frames for lists
    list_body:
        inherits_from: standard
        x_hook: right
        x_offset: 1
        y_hook: top
        y_offset: 0
        
    list_container:
        inherits_from: standard
        y_hook: top
        
    list_item:
        inherits_from: standard
        height_mode: fixed
        max_height: 1
        width_mode: auto
        
    toc_item:
        inherits_from: list_item
        
        
    # frames for block_quotes
    block_quote_container:
        inherits_from: standard
        lines_below: 1
        right_indent: 4
        x_offset: 4
        y_align: top
        y_hook: top
        y_offset: 1

    
    # frames for page numbers
    #pagenum_right: *id011
    
content:
    section_title1:
        x_align: center
    section_title2:
        x_align: center
    section_title3:
        x_align: left
    section_title4:
        x_align: left
    section_title5:
        x_align: left
    section_title6:
        x_align: left
    document_title:
        x_align: center
    topic:
        x_align: left
    default:
        x_align: left
    
    
hyphenator:

    default: null
    
    hyphen_de_DE:
        class_path: hyphen.hyphenator
        language: de_DE
        
    hyphen_en_US:
        inherits_from: hyphen_de_DE
        language: en_US
        
        
        
translator:
    YABT-en: # British contracted Braille. requires YABT
        class_path: translators.YABTrans
        
    default: null
    
    emphasis:
        class_path: translators.UpperTrans
        
    upper:
        inherits_from: emphasis
        
    louis-de: # German Braille. requires liblouis and the Pythin bindings
        class_path: translators.Louis
        mode: 0
        tables:
        - de-de-g1.ctb
        
    louis-de2:
        inherits_from: louis-de
        tables:
        - de-de-g2.ctb
        
    louis-en2:
        inherits_from: louis-de
        tables:
        - en-US-g2.ctb
        
        
wrapper:
    standard: # no support for hyphenation, simple rectangular outline
        class_path: textwrap.TextWrapper
        
    standard2: # supports hyphenation, requires PyHyphen package
        class_path: textwrap2.TextWrapper
        
    default:
        inherits_from: standard

    indent2:
        inherits_from: default
        initial_indent: !!python/unicode '  '

    pending2:
        inherits_from: default
        subsequent_indent: !!python/unicode '  '
        


transition:
    standard:
        text: "-"
        translator: null
        ratio: 0.5
    default:
        inherits_from: standard
        
        